name: Reusable Lint Workflow

on:
  workflow_call:

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest
    steps:
      - name: Setup Node.js Environment
        uses: ./.github/actions/setup-node-env

      - name: Run linters
        run: npm run lint 