name: Deploy to Cloudflare Pages

on:
  workflow_dispatch:

jobs:
  lint:
    uses: ./.github/workflows/lint.yml

  unit-tests:
    name: Unit Tests
    runs-on: ubuntu-latest
    needs: lint
    steps:
      - name: Setup Node.js Environment
        uses: ./.github/actions/setup-node-env

      - name: Run unit tests
        run: npm run test

  deploy:
    name: Deploy to Cloudflare Pages
    runs-on: ubuntu-latest
    needs: [lint, unit-tests]
    environment: production
    permissions:
      contents: read
      deployments: write
    steps:
      - name: Setup Node.js Environment
        uses: ./.github/actions/setup-node-env

      - name: Build project
        run: npm run build

      - name: Deploy to Cloudflare Pages
        uses: cloudflare/wrangler-action@v3
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          command: pages deploy dist --project-name=web-flashcards
